[package]
name = "examshuffler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.5", features=['derive']}
rand = "0.8.5"
# tectonic = "0.9.0"
csv = "1.1.6"
thiserror ="1.0"